version: '3'

services:
  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: passnfly

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: always
    
  passnfly_api:
    image: passnfly_api:0.1.0-RC1
    restart: always
    ports:
      - "5000:5000"
    environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASS: helloworld
        MYSQL_DATABASE: passnfly
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_QUEUE: airports_api

  passnfly_async:
    image: passnfly_async:0.1.0-RC1
    restart: always
    environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASS: helloworld
        MYSQL_DATABASE: passnfly
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_QUEUE: airports_api
