version: '3'

services:
  mysql:
    image: mysql:8.0.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
